### ISSUE TITLE
Manual Mode channel seek order by Band/Channel instead of Freq.

### ISSUE THREAD

**Issue by derFrickler** [Dvogonen/cyclop_plus#17]
First of all: Thanks for the great work! The project works really nice! 

In my opinion it would be more useful to run through the channels by Band and not ordered by frequency. 
Normally you know which band you are on and you don't change that very often. Although e.g. if you are on A7 and want to change to B3, its more obvious to go 4 ch up thant running along the band until you reach B3.

Maybe this could be added as an option to your code (rx5808-pro-diversity has this feature)
To do it hard-wired, all that has to be done is replacing the getPosition function to not use the positions table:
//uint16_t getPosition( uint8_t channel ) {
//  return pgm_read_byte_near(positions + channel);
//}
uint16_t getPosition( uint8_t channel ) {
  return channel;
}

**Comment by Dvogonen** [comment]
Referring only to frequencies rather than bands when stepping and searching is a conscious decision.
I personally do not like FPV equipment that makes you first select a band and then a channel within that band. One specific aspect I really dislike is that people do not realize that they might be using virtually the same frequency when they are using two different band/position settings. This is outright dangerous. Knowing the frequency is much more important than the band/position setting.
