### ISSUE TITLE
Add L channels ??

### ISSUE THREAD

**Issue by mattyra** [Dvogonen/cyclop_plus#20]
Hello, Is it possible to add the L Channels for the band ??

https://github.com/sheaivey/rx5808-pro-diversity/issues/75

**Comment by Dvogonen** [comment]
I just checked the datasheet for the RichWave receiver unit that is used by the Cyclops googles and according to it, the lowest possible frequency the receiver can receive is 5725 KHz. The L band consists of eight frequencies below 5725 (5362KHz-5621KHz). If the datasheet is correct, it is technically impossible to implement L-band support.
That said, harware can sometimes be used at out of spec settings. 5725 KHz is the lower end of the legal 5.8 MHz band, so it makes little sense for manufacturers to claim support for a wider frequency range, even if the hardware supports it. I am however not in a position to experiment with trying to use the receiver at L-band settings, since I do not have any transmitter that is L-band capable. So, for the moment the answer to the question is; 
No, it is not possible to implement L-band support.

**Comment by mattyra** [comment]
Are you reopening this now ??

**Comment by Dvogonen** [comment]
Yes, I have bought an L-Band capable transmitter and will test if it is possible to tweak the transmitter of the Cyclops to receive the lower frequencies. The specifications clearly says that it is not possible, but you never know. I will do the testing in the Cyclops++ project, but if things go well I will add support for both cyclops+ and ++

**Comment by mattyra** [comment]
Well thats great, let me know if you want the code tested..

Matt

**Comment by Dvogonen** [comment]
I have just released 1.5 with full support for the L-band.
